# Generated by Django 2.0 on 2017-12-20 20:38

import django.contrib.postgres.fields
import django.utils.timezone
import panta.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modified"
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        blank=True,
                        help_text="Titles, in some langauges as suffix.",
                        max_length=20,
                        verbose_name="prefix",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="last name"),
                ),
                (
                    "suffix",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="suffix"
                    ),
                ),
                (
                    "born",
                    models.DateField(
                        blank=True, null=True, verbose_name="date of birth"
                    ),
                ),
                ("bio", models.TextField(verbose_name="biograpyh")),
            ],
            options={
                "verbose_name_plural": "authors",
                "verbose_name": "author",
            },
        ),
        migrations.CreateModel(
            name="HistoricalOriginalSegment",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True,
                        blank=True,
                        db_index=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="date created"
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="last modified"
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        help_text="Segments get ordered by their positions.",
                        verbose_name="positon",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="(First) page of this segment in the work. You may use Arabic numerals (1,2,3,...), Roman numerals (in upper case, e.g. I,II,III,...) or the alphabet in lower case (a - z).",
                        max_length=7,
                        null=True,
                        validators=[panta.validators.get_bullet_format],
                        verbose_name="page",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        max_length=10,
                        validators=[panta.validators.valid_tag],
                        verbose_name="tag",
                    ),
                ),
                (
                    "classes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=15),
                        blank=True,
                        default=list,
                        size=None,
                        validators=[panta.validators.valid_classes],
                        verbose_name="classes",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        validators=[panta.validators.valid_segment],
                        verbose_name="content",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="reference"
                    ),
                ),
                (
                    "history_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("history_date", models.DateTimeField()),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
                "verbose_name": "historical original segment",
            },
        ),
        migrations.CreateModel(
            name="HistoricalOriginalWork",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True,
                        blank=True,
                        db_index=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="date created"
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="last modified"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="title"
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="subtitle"
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        db_index=True,
                        help_text="Public identifier of this work.",
                        max_length=4,
                        validators=[
                            panta.validators.is_ascii_alphanumeric_character
                        ],
                        verbose_name="abbreviation",
                    ),
                ),
                ("type", models.CharField(max_length=10, verbose_name="type")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("de", "German")],
                        help_text="Select the langauge of this work.",
                        max_length=7,
                        verbose_name="language",
                    ),
                ),
                ("private", models.BooleanField(verbose_name="private")),
                (
                    "published",
                    models.CharField(
                        max_length=11, verbose_name="published in"
                    ),
                ),
                (
                    "edition",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="edition"
                    ),
                ),
                (
                    "isbn",
                    models.CharField(
                        blank=True, max_length=17, verbose_name="ISBN"
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True, max_length=70, verbose_name="publisher"
                    ),
                ),
                (
                    "history_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("history_date", models.DateTimeField()),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
                "verbose_name": "historical original work",
            },
        ),
        migrations.CreateModel(
            name="HistoricalTranslatedSegment",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True,
                        blank=True,
                        db_index=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        validators=[panta.validators.valid_segment],
                        verbose_name="content",
                    ),
                ),
                (
                    "history_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("history_date", models.DateTimeField()),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
                "verbose_name": "historical translated segment",
            },
        ),
        migrations.CreateModel(
            name="HistoricalTranslatedWork",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True,
                        blank=True,
                        db_index=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="date created"
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="last modified"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="title"
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="subtitle"
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        db_index=True,
                        help_text="Public identifier of this work.",
                        max_length=4,
                        validators=[
                            panta.validators.is_ascii_alphanumeric_character
                        ],
                        verbose_name="abbreviation",
                    ),
                ),
                ("type", models.CharField(max_length=10, verbose_name="type")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("de", "German")],
                        help_text="Select the langauge of this work.",
                        max_length=7,
                        verbose_name="language",
                    ),
                ),
                ("private", models.BooleanField(verbose_name="private")),
                (
                    "protected",
                    models.BooleanField(
                        help_text="Gets checked when work is ready for amending.",
                        verbose_name="protected",
                    ),
                ),
                (
                    "history_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("history_date", models.DateTimeField()),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
                "verbose_name": "historical translated work",
            },
        ),
        migrations.CreateModel(
            name="Licence",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modified"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="title"
                    ),
                ),
                ("description", models.TextField(verbose_name="description")),
            ],
            options={
                "verbose_name_plural": "licences",
                "get_latest_by": "created",
                "abstract": False,
                "verbose_name": "licence",
            },
        ),
        migrations.CreateModel(
            name="OriginalSegment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modified"
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        help_text="Segments get ordered by their positions.",
                        verbose_name="positon",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="(First) page of this segment in the work. You may use Arabic numerals (1,2,3,...), Roman numerals (in upper case, e.g. I,II,III,...) or the alphabet in lower case (a - z).",
                        max_length=7,
                        null=True,
                        validators=[panta.validators.get_bullet_format],
                        verbose_name="page",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        max_length=10,
                        validators=[panta.validators.valid_tag],
                        verbose_name="tag",
                    ),
                ),
                (
                    "classes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=15),
                        blank=True,
                        default=list,
                        size=None,
                        validators=[panta.validators.valid_classes],
                        verbose_name="classes",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        validators=[panta.validators.valid_segment],
                        verbose_name="content",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="reference"
                    ),
                ),
            ],
            options={
                "ordering": ("position",),
                "verbose_name_plural": "original segments",
                "get_latest_by": "created",
                "abstract": False,
                "verbose_name": "original segment",
            },
        ),
        migrations.CreateModel(
            name="OriginalWork",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modified"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="title"
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="subtitle"
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        db_index=True,
                        help_text="Public identifier of this work.",
                        max_length=4,
                        validators=[
                            panta.validators.is_ascii_alphanumeric_character
                        ],
                        verbose_name="abbreviation",
                    ),
                ),
                ("type", models.CharField(max_length=10, verbose_name="type")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("de", "German")],
                        help_text="Select the langauge of this work.",
                        max_length=7,
                        verbose_name="language",
                    ),
                ),
                ("private", models.BooleanField(verbose_name="private")),
                (
                    "published",
                    models.CharField(
                        max_length=11, verbose_name="published in"
                    ),
                ),
                (
                    "edition",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="edition"
                    ),
                ),
                (
                    "isbn",
                    models.CharField(
                        blank=True, max_length=17, verbose_name="ISBN"
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True, max_length=70, verbose_name="publisher"
                    ),
                ),
            ],
            options={
                "permissions": (("view_originalwork", "View original work"),),
                "verbose_name_plural": "original works",
                "get_latest_by": "created",
                "abstract": False,
                "verbose_name": "original work",
            },
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modified"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="title"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="type"
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=15,
                        verbose_name="abbreviation",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="author"
                    ),
                ),
                (
                    "published",
                    models.CharField(
                        blank=True, max_length=11, verbose_name="published in"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("de", "German")],
                        db_index=True,
                        max_length=7,
                        verbose_name="language",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "references",
                "verbose_name": "reference",
            },
        ),
        migrations.CreateModel(
            name="SegmentDraft",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="date created",
                    ),
                ),
                ("content", models.TextField(verbose_name="content")),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        db_index=True, verbose_name="positon"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "translated segment drafts",
                "get_latest_by": "created",
                "abstract": False,
                "verbose_name": "translated segment draft",
            },
        ),
        migrations.CreateModel(
            name="TranslatedSegment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modified"
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        help_text="Segments get ordered by their positions.",
                        verbose_name="positon",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="(First) page of this segment in the work. You may use Arabic numerals (1,2,3,...), Roman numerals (in upper case, e.g. I,II,III,...) or the alphabet in lower case (a - z).",
                        max_length=7,
                        null=True,
                        validators=[panta.validators.get_bullet_format],
                        verbose_name="page",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        max_length=10,
                        validators=[panta.validators.valid_tag],
                        verbose_name="tag",
                    ),
                ),
                (
                    "classes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=15),
                        blank=True,
                        default=list,
                        size=None,
                        validators=[panta.validators.valid_classes],
                        verbose_name="classes",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        validators=[panta.validators.valid_segment],
                        verbose_name="content",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="reference"
                    ),
                ),
            ],
            options={
                "ordering": ("position",),
                "verbose_name_plural": "translated segments",
                "get_latest_by": "created",
                "abstract": False,
                "verbose_name": "translated segment",
            },
        ),
        migrations.CreateModel(
            name="TranslatedWork",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modified"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="title"
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="subtitle"
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        db_index=True,
                        help_text="Public identifier of this work.",
                        max_length=4,
                        validators=[
                            panta.validators.is_ascii_alphanumeric_character
                        ],
                        verbose_name="abbreviation",
                    ),
                ),
                ("type", models.CharField(max_length=10, verbose_name="type")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("de", "German")],
                        help_text="Select the langauge of this work.",
                        max_length=7,
                        verbose_name="language",
                    ),
                ),
                ("private", models.BooleanField(verbose_name="private")),
                (
                    "protected",
                    models.BooleanField(
                        help_text="Gets checked when work is ready for amending.",
                        verbose_name="protected",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("view_translatedwork", "View translated work"),
                ),
                "verbose_name_plural": "translated works",
                "get_latest_by": "created",
                "abstract": False,
                "verbose_name": "translated work",
            },
        ),
        migrations.CreateModel(
            name="Trustee",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="name"
                    ),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "code",
                    models.CharField(
                        help_text="Cannot be changed!",
                        max_length=5,
                        unique=True,
                        verbose_name="code",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
