# Generated by Django 2.0.1 on 2018-01-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("panta", "0002_auto_20171220_2038")]

    operations = [
        migrations.AlterField(
            model_name="historicaloriginalsegment",
            name="position",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                help_text="Segments get ordered by their positions.",
                verbose_name="position",
            ),
        ),
        migrations.AlterField(
            model_name="originalsegment",
            name="position",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                help_text="Segments get ordered by their positions.",
                verbose_name="position",
            ),
        ),
        migrations.AlterField(
            model_name="segmentdraft",
            name="position",
            field=models.PositiveSmallIntegerField(
                db_index=True, verbose_name="position"
            ),
        ),
        migrations.AlterField(
            model_name="translatedsegment",
            name="position",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                help_text="Segments get ordered by their positions.",
                verbose_name="position",
            ),
        ),
    ]
