# Generated by Django 2.0 on 2017-12-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("panta", "0002_auto_20171220_2038")]

    operations = [
        migrations.AlterField(
            model_name="segmentdraft",
            name="content",
            field=models.TextField(blank=True, verbose_name="content"),
        )
    ]
