# Generated by Django 2.0.1 on 2018-01-22 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("panta", "0003_auto_20171224_1701"),
        ("panta", "0003_auto_20180111_0957"),
    ]

    operations = []
