# Generated by Django 2.0.3 on 2018-04-10 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("panta", "0004_merge_20180122_1439"),
    ]

    operations = [
        migrations.CreateModel(
            name="SegmentComment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modified"
                    ),
                ),
                (
                    "content",
                    models.TextField(max_length=2000, verbose_name="content"),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comments",
                        to="panta.TranslatedSegment",
                        verbose_name="segment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "get_latest_by": "created",
                "abstract": False,
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
            },
        )
    ]
