# Generated by Django 2.0.4 on 2018-04-25 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("panta", "0008_auto_20180417_0840")]

    operations = [
        migrations.RemoveField(model_name="segmentcomment", name="segment"),
        migrations.AddField(
            model_name="segmentcomment",
            name="position",
            field=models.PositiveSmallIntegerField(
                db_index=True, default=1, verbose_name="position"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="segmentcomment",
            name="work",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="segmentcomments",
                to="panta.TranslatedWork",
                verbose_name="work",
            ),
            preserve_default=False,
        ),
    ]
