# Generated by Django 2.0.4 on 2018-05-03 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("panta", "0010_segmentcomment_to_delete")]

    operations = [
        migrations.AlterModelOptions(
            name="segmentcomment",
            options={
                "get_latest_by": "created",
                "verbose_name": "segment comment",
                "verbose_name_plural": "segment comments",
            },
        ),
        migrations.AlterField(
            model_name="segmentcomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="segmentcomments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
