# Generated by Django 2.0.6 on 2018-06-17 18:49

import django.contrib.postgres.fields
import panta.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("panta", "0011_auto_20180503_1610")]

    operations = [
        migrations.AlterField(
            model_name="historicaloriginalsegment",
            name="classes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=30),
                blank=True,
                default=list,
                size=None,
                validators=[panta.validators.valid_classes],
                verbose_name="classes",
            ),
        ),
        migrations.AlterField(
            model_name="originalsegment",
            name="classes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=30),
                blank=True,
                default=list,
                size=None,
                validators=[panta.validators.valid_classes],
                verbose_name="classes",
            ),
        ),
        migrations.AlterField(
            model_name="translatedsegment",
            name="classes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=30),
                blank=True,
                default=list,
                size=None,
                validators=[panta.validators.valid_classes],
                verbose_name="classes",
            ),
        ),
    ]
