# Generated by Django 2.0.6 on 2018-06-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("panta", "0012_auto_20180617_1849")]

    operations = [
        migrations.AddField(
            model_name="historicaloriginalsegment",
            name="key",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="key"
            ),
        ),
        migrations.AddField(
            model_name="originalsegment",
            name="key",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="key"
            ),
        ),
    ]
