# Generated by Django 2.0.6 on 2018-07-08 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("panta", "0013_auto_20180619_0844")]

    operations = [
        migrations.AlterField(
            model_name="historicaltranslatedsegment",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="historicaltranslatedsegments",
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
