# Generated by Django 2.0.6 on 2018-07-09 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("panta", "0014_auto_20180708_2005"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalAuthor",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True,
                        blank=True,
                        db_index=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="date created"
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="last modified"
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        blank=True,
                        help_text="Titles, in some langauges as suffix.",
                        max_length=20,
                        verbose_name="prefix",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="last name"),
                ),
                (
                    "suffix",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="suffix"
                    ),
                ),
                (
                    "born",
                    models.DateField(
                        blank=True, null=True, verbose_name="date of birth"
                    ),
                ),
                ("bio", models.TextField(verbose_name="biograpyh")),
                (
                    "history_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                ("history_date", models.DateTimeField()),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical author",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
        ),
        migrations.CreateModel(
            name="HistoricalLicence",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True,
                        blank=True,
                        db_index=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="date created"
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="last modified"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="title"
                    ),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "history_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                ("history_date", models.DateTimeField()),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical licence",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
        ),
        migrations.CreateModel(
            name="HistoricalReference",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True,
                        blank=True,
                        db_index=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="date created"
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="last modified"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="title"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="type"
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=15,
                        verbose_name="abbreviation",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="author"
                    ),
                ),
                (
                    "published",
                    models.CharField(
                        blank=True, max_length=11, verbose_name="published in"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("de", "German")],
                        db_index=True,
                        max_length=7,
                        verbose_name="language",
                    ),
                ),
                (
                    "history_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                ("history_date", models.DateTimeField()),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical reference",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
        ),
        migrations.CreateModel(
            name="HistoricalTrustee",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True,
                        blank=True,
                        db_index=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="name"
                    ),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Cannot be changed!",
                        max_length=5,
                        verbose_name="code",
                    ),
                ),
                (
                    "history_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                ("history_date", models.DateTimeField()),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical trustee",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
        ),
    ]
