# Generated by Django 2.0.8 on 2018-10-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("panta", "0018_update_deepl_records")]

    operations = [
        migrations.AlterField(
            model_name="basetranslation",
            name="language",
            field=models.CharField(
                choices=[
                    ("de", "German"),
                    ("en", "English"),
                    ("sw", "Swahili"),
                    ("tr", "Turkish"),
                ],
                db_index=True,
                max_length=7,
                verbose_name="language",
            ),
        ),
        migrations.AlterField(
            model_name="historicaloriginalwork",
            name="language",
            field=models.CharField(
                choices=[
                    ("de", "German"),
                    ("en", "English"),
                    ("sw", "Swahili"),
                    ("tr", "Turkish"),
                ],
                help_text="Select the langauge of this work.",
                max_length=7,
                verbose_name="language",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreference",
            name="language",
            field=models.CharField(
                choices=[
                    ("de", "German"),
                    ("en", "English"),
                    ("sw", "Swahili"),
                    ("tr", "Turkish"),
                ],
                db_index=True,
                max_length=7,
                verbose_name="language",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltranslatedwork",
            name="language",
            field=models.CharField(
                choices=[
                    ("de", "German"),
                    ("en", "English"),
                    ("sw", "Swahili"),
                    ("tr", "Turkish"),
                ],
                help_text="Select the langauge of this work.",
                max_length=7,
                verbose_name="language",
            ),
        ),
        migrations.AlterField(
            model_name="originalwork",
            name="language",
            field=models.CharField(
                choices=[
                    ("de", "German"),
                    ("en", "English"),
                    ("sw", "Swahili"),
                    ("tr", "Turkish"),
                ],
                help_text="Select the langauge of this work.",
                max_length=7,
                verbose_name="language",
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="language",
            field=models.CharField(
                choices=[
                    ("de", "German"),
                    ("en", "English"),
                    ("sw", "Swahili"),
                    ("tr", "Turkish"),
                ],
                db_index=True,
                max_length=7,
                verbose_name="language",
            ),
        ),
        migrations.AlterField(
            model_name="translatedwork",
            name="language",
            field=models.CharField(
                choices=[
                    ("de", "German"),
                    ("en", "English"),
                    ("sw", "Swahili"),
                    ("tr", "Turkish"),
                ],
                help_text="Select the langauge of this work.",
                max_length=7,
                verbose_name="language",
            ),
        ),
    ]
