# Generated by Django 2.0.9 on 2018-10-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("panta", "0019_auto_20181010_0906")]

    operations = [
        migrations.AlterField(
            model_name="historicaltranslatedsegment",
            name="relative_id",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="relative ID"
            ),
        )
    ]
