# Generated by Django 2.0.9 on 2018-10-30 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("panta", "0021_auto_20181022_0711")]

    operations = [
        migrations.AddField(
            model_name="segmentcomment",
            name="vote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="segmentcomments",
                to="panta.Vote",
                verbose_name="vote",
            ),
        )
    ]
