# Generated by Django 2.0.8 on 2018-11-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("panta", "0022_segmentcomment_vote")]

    operations = [
        migrations.AddField(
            model_name="translatedsegment",
            name="progress",
            field=models.CharField(
                choices=[
                    ("blank", "blank"),
                    ("in_translation", "in translation"),
                    ("translation_done", "translation done"),
                ],
                default="blank",
                max_length=16,
                verbose_name="progress",
            ),
        )
    ]
