# Generated by Django 2.0.9 on 2018-11-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("panta", "0028_remove_translatedsegment_progress")]

    operations = [
        migrations.AddField(
            model_name="translatedsegment",
            name="progress",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "blank"),
                    (1, "in translation"),
                    (2, "translation done"),
                    (3, "in review"),
                ],
                default=0,
                verbose_name="progress",
            ),
        )
    ]
