# Generated by Django 2.0.9 on 2018-12-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("panta", "0032_auto_20181213_2139")]

    operations = [
        migrations.AlterField(
            model_name="translatedsegment",
            name="progress",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "blank"),
                    (1, "in translation"),
                    (2, "translation done"),
                    (3, "in review"),
                    (4, "review done"),
                    (5, "trustee done"),
                ],
                default=0,
                verbose_name="progress",
            ),
        )
    ]
