# Generated by Django 2.0.13 on 2019-03-19 02:33

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("panta", "0035_auto_20190201_0920")]

    operations = [
        migrations.CreateModel(
            name="ImportantHeading",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="number"
                    ),
                ),
                (
                    "first_position",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="first position"
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(verbose_name="position"),
                ),
                ("tag", models.CharField(max_length=10, verbose_name="tag")),
                (
                    "classes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=30),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="classes",
                    ),
                ),
                ("content", models.TextField(verbose_name="content")),
                (
                    "translation_done",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="translaton done"
                    ),
                ),
                (
                    "review_done",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="review done"
                    ),
                ),
                (
                    "trustee_done",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="trustee done"
                    ),
                ),
                (
                    "segments_count",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="segments count"
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        help_text=(
                            "last_modified of the segment in the current "
                            "chapter with the most recent modification when "
                            "last updated."
                        ),
                        verbose_name="date",
                    ),
                ),
                (
                    "segment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="important_heading",
                        to="panta.TranslatedSegment",
                        verbose_name="segment",
                    ),
                ),
                (
                    "segments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="important_headings",
                        to="panta.TranslatedSegment",
                        verbose_name="segments",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="important_headings",
                        to="panta.TranslatedWork",
                        verbose_name="work",
                    ),
                ),
            ],
            options={
                "verbose_name": "important heading",
                "verbose_name_plural": "important headings",
                "ordering": ("position",),
            },
        ),
        migrations.AlterUniqueTogether(
            name="importantheading", unique_together={("work", "number")}
        ),
    ]
