# Generated by Django 2.0.13 on 2019-04-15 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('panta', '0039_auto_20190408_1001')]

    operations = [
        migrations.AddField(
            model_name='historicaltranslatedsegment',
            name='chapter',
            field=models.ForeignKey(
                blank=True,
                null=True,
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='panta.ImportantHeading',
                verbose_name='chapter',
            ),
        ),
        migrations.AddField(
            model_name='translatedsegment',
            name='chapter',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='segments',
                to='panta.ImportantHeading',
                verbose_name='chapter',
            ),
        ),
    ]
