# Generated by Django 2.0.13 on 2019-04-22 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'panta',
            '0043_make_abbreviations_case_sensitive_and_update_references',
        )
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloriginalsegment',
            name='reference',
            field=models.CharField(max_length=50, verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='originalsegment',
            name='reference',
            field=models.CharField(max_length=50, verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='translatedsegment',
            name='chapter',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='segments',
                to='panta.ImportantHeading',
                verbose_name='chapter',
            ),
        ),
        migrations.AlterField(
            model_name='translatedsegment',
            name='reference',
            field=models.CharField(max_length=50, verbose_name='reference'),
        ),
    ]
