# Generated by Django 2.0.13 on 2019-05-02 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('panta', '0044_auto_20190422_2021')]

    operations = [
        migrations.AlterModelOptions(
            name='importantheading',
            options={
                'verbose_name': 'important heading',
                'verbose_name_plural': 'important headings',
            },
        ),
        migrations.AddField(
            model_name='historicaltranslatedsegment',
            name='history_relation',
            field=models.ForeignKey(
                db_constraint=False,
                default=0,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='segment_history',
                to='panta.TranslatedSegment',
            ),
            preserve_default=False,
        ),
    ]
