# Generated by Django 2.0.13 on 2019-05-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('panta', '0048_populate_work_statistics')]

    operations = [
        migrations.AlterField(
            model_name='historicaloriginalsegment',
            name='position',
            field=models.PositiveIntegerField(
                db_index=True,
                help_text='Segments get ordered by their positions.',
                verbose_name='position',
            ),
        ),
        migrations.AlterField(
            model_name='historicaloriginalwork',
            name='abbreviation',
            field=models.SlugField(
                help_text='Public identifier of this work.',
                max_length=30,
                verbose_name='abbreviation',
            ),
        ),
        migrations.AlterField(
            model_name='historicaloriginalwork',
            name='published',
            field=models.CharField(
                blank=True, max_length=11, verbose_name='published in'
            ),
        ),
        migrations.AlterField(
            model_name='historicaloriginalwork',
            name='title',
            field=models.CharField(
                db_index=True, max_length=150, verbose_name='title'
            ),
        ),
        migrations.AlterField(
            model_name='historicaloriginalwork',
            name='type',
            field=models.CharField(
                choices=[
                    ('book', 'Book'),
                    ('periodical', 'Periodical'),
                    ('manuscript', 'Manuscript'),
                ],
                max_length=10,
                verbose_name='type',
            ),
        ),
        migrations.AlterField(
            model_name='historicaltranslatedwork',
            name='abbreviation',
            field=models.SlugField(
                help_text='Public identifier of this work.',
                max_length=30,
                verbose_name='abbreviation',
            ),
        ),
        migrations.AlterField(
            model_name='historicaltranslatedwork',
            name='title',
            field=models.CharField(
                db_index=True, max_length=150, verbose_name='title'
            ),
        ),
        migrations.AlterField(
            model_name='historicaltranslatedwork',
            name='type',
            field=models.CharField(
                choices=[
                    ('book', 'Book'),
                    ('periodical', 'Periodical'),
                    ('manuscript', 'Manuscript'),
                ],
                max_length=10,
                verbose_name='type',
            ),
        ),
        migrations.AlterField(
            model_name='importantheading',
            name='first_position',
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name='first position'
            ),
        ),
        migrations.AlterField(
            model_name='importantheading',
            name='position',
            field=models.PositiveIntegerField(verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='importantheading',
            name='segments_count',
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name='segments count'
            ),
        ),
        migrations.AlterField(
            model_name='originalsegment',
            name='position',
            field=models.PositiveIntegerField(
                db_index=True,
                help_text='Segments get ordered by their positions.',
                verbose_name='position',
            ),
        ),
        migrations.AlterField(
            model_name='originalwork',
            name='abbreviation',
            field=models.SlugField(
                help_text='Public identifier of this work.',
                max_length=30,
                verbose_name='abbreviation',
            ),
        ),
        migrations.AlterField(
            model_name='originalwork',
            name='published',
            field=models.CharField(
                blank=True, max_length=11, verbose_name='published in'
            ),
        ),
        migrations.AlterField(
            model_name='originalwork',
            name='title',
            field=models.CharField(
                db_index=True, max_length=150, verbose_name='title'
            ),
        ),
        migrations.AlterField(
            model_name='originalwork',
            name='type',
            field=models.CharField(
                choices=[
                    ('book', 'Book'),
                    ('periodical', 'Periodical'),
                    ('manuscript', 'Manuscript'),
                ],
                max_length=10,
                verbose_name='type',
            ),
        ),
        migrations.AlterField(
            model_name='segmentcomment',
            name='position',
            field=models.PositiveIntegerField(
                db_index=True, verbose_name='position'
            ),
        ),
        migrations.AlterField(
            model_name='segmentdraft',
            name='position',
            field=models.PositiveIntegerField(
                db_index=True, verbose_name='position'
            ),
        ),
        migrations.AlterField(
            model_name='translatedsegment',
            name='position',
            field=models.PositiveIntegerField(
                db_index=True,
                help_text='Segments get ordered by their positions.',
                verbose_name='position',
            ),
        ),
        migrations.AlterField(
            model_name='translatedwork',
            name='abbreviation',
            field=models.SlugField(
                help_text='Public identifier of this work.',
                max_length=30,
                verbose_name='abbreviation',
            ),
        ),
        migrations.AlterField(
            model_name='translatedwork',
            name='title',
            field=models.CharField(
                db_index=True, max_length=150, verbose_name='title'
            ),
        ),
        migrations.AlterField(
            model_name='translatedwork',
            name='type',
            field=models.CharField(
                choices=[
                    ('book', 'Book'),
                    ('periodical', 'Periodical'),
                    ('manuscript', 'Manuscript'),
                ],
                max_length=10,
                verbose_name='type',
            ),
        ),
        migrations.AlterField(
            model_name='workstatistics',
            name='authorized_count',
            field=models.PositiveIntegerField(
                default=0, verbose_name='authorized'
            ),
        ),
        migrations.AlterField(
            model_name='workstatistics',
            name='reviewed_count',
            field=models.PositiveIntegerField(
                default=0, verbose_name='reviewed'
            ),
        ),
        migrations.AlterField(
            model_name='workstatistics',
            name='segments',
            field=models.PositiveIntegerField(verbose_name='segments'),
        ),
        migrations.AlterField(
            model_name='workstatistics',
            name='translated_count',
            field=models.PositiveIntegerField(
                default=0, verbose_name='translated'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='originalwork', unique_together=set()
        ),
        migrations.AlterUniqueTogether(
            name='translatedwork', unique_together=set()
        ),
        migrations.AlterIndexTogether(
            name='originalwork', index_together=set()
        ),
        migrations.AlterIndexTogether(
            name='translatedwork', index_together=set()
        ),
    ]
