from django.db import migrations

# All references that should be changed that are currently found on production

CHANGE = (
    'AA IV',
    'AA V',
    'AA V.1',
    'AA V.2',
    'AA V.3',
    'AA VI.1',
    'AA VI.2',
    'AA IV',
    'AA V',
    'AA V.1',
    'AA V.2',
    'AA V.3',
    'AA VI.1',
    'AA VI.2',
    'GC I',
    'GC III',
    'GC III.1',
    'GC III.2',
    'GC III.3',
    'GC III.4',
    'GC III.5',
    'GC III.6',
    'GC III.7',
    'GC IV.1',
    'GC IV.2',
    'GC IV.3',
    'GC IV.4',
    'GC IX.1',
    'GC IX.2',
    'GC IX.3',
    'GC IX.4',
    'GC V',
    'GC V.1',
    'GC V.2',
    'GC V.3',
    'GC V.4',
    'GC VI.1',
    'GC VI.2',
    'GC VI.3',
    'GC VII.1',
    'GC VII.2',
    'GC VII.3',
    'GC VII.4',
    'GC VIII.1',
    'GC VIII.2',
    'GC X.1',
    'GC XI.1',
    'GC XI.2',
    'GC XI.3',
    'GC XI.4',
    'GC XII.1',
    'GC XII.2',
    'MM III',
    'MM IX',
    'MM IX',
    'MM IX',
    'MM IX.1',
    'MM IX.2',
    'MM IX.3',
    'MM V',
    'MM V.1',
    'MM V.2',
    'MM V.3',
    'MM V.4',
    'MM VI.1',
    'MM VI.2',
    'MM VI.3',
    'MM VII',
    'MM VII',
    'MM VII.1',
    'MM VII.2',
    'MM VII.3',
    'MM VII.4',
    'MM VIII',
    'MM VIII',
    'MM VIII.1',
    'MM VIII.2',
    'MM VIII.3',
    'MM VIII.4',
    'MM X',
    'MM X',
    'MM X.1',
    'MM X.2',
    'MM X.3',
    'MM XI',
    'MM XI',
    'MM XI',
    'MM XI.1',
    'MM XI.2',
    'MM XI.3',
    'MM XI.4',
    'MM XI.5',
    'MM XII.1',
    'MM XII.2',
    'MM XII.3',
    'MM XII.4',
    'MM XII.5',
    'MM XII.6',
    'MM XIII',
    'MM XIII.1',
    'MM XIII.2',
    'MM XIII.3',
    'MM XIII.4',
    'MM XIII.5',
    'MM XIII.6',
    'MM XIII.7',
    'MM XIV',
    'MM XIV.1',
    'MM XIV.2',
    'MM XIV.3',
    'MM XIV.4',
    'MM XV.1',
)


def lowercase_roman_numerals(apps, schema_editor):
    OriginalSegment = apps.get_model('panta', 'OriginalSegment')
    TranslatedSegment = apps.get_model('panta', 'TranslatedSegment')

    for old in CHANGE:
        parts = old.split()
        new = f'{parts[0]} {parts[1].lower()}'
        OriginalSegment.objects.filter(reference=old).update(reference=new)
        TranslatedSegment.objects.filter(reference=old).update(reference=new)


class Migration(migrations.Migration):

    dependencies = [('panta', '0049_auto_20190515_1216')]

    operations = [migrations.RunPython(lowercase_roman_numerals)]
