# Generated by Django 2.0.13 on 2019-05-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('panta', '0050_lowercase_roman_numerals_in_references')]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(
                blank=True, max_length=40, verbose_name='slug'
            ),
        )
    ]
