# Generated by Django 2.0.13 on 2019-05-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('panta', '0052_populate_tag_slug')]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(
                max_length=40, unique=True, verbose_name='slug'
            ),
        )
    ]
