# Generated by Django 2.0.13 on 2019-05-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('panta', '0053_auto_20190517_1015')]

    operations = [
        migrations.AddField(
            model_name='historicaloriginalwork',
            name='published_2',
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name='published in'
            ),
        ),
        migrations.AddField(
            model_name='originalwork',
            name='published_2',
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name='published in'
            ),
        ),
    ]
