# Generated by Django 2.0.13 on 2019-05-23 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('panta', '0055_duplicate_published')]

    operations = [
        migrations.RemoveField(
            model_name='historicaloriginalwork', name='published'
        ),
        migrations.RemoveField(model_name='originalwork', name='published'),
    ]
