# Generated by Django 2.0.13 on 2019-05-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('panta', '0056_auto_20190523_2116')]

    operations = [
        migrations.AddField(
            model_name='historicaloriginalwork',
            name='published',
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name='published in'
            ),
        ),
        migrations.AddField(
            model_name='originalwork',
            name='published',
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name='published in'
            ),
        ),
    ]
