# Generated by Django 2.0.13 on 2019-05-23 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('panta', '0058_populate_published')]

    operations = [
        migrations.RemoveField(
            model_name='historicaloriginalwork', name='published_2'
        ),
        migrations.RemoveField(model_name='originalwork', name='published_2'),
    ]
