# Generated by Django 2.0.13 on 2019-06-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('panta', '0062_auto_20190625_2126')]

    operations = [
        migrations.AddField(
            model_name='historicaloriginalwork',
            name='key',
            field=models.CharField(
                blank=True, max_length=30, verbose_name='key'
            ),
        ),
        migrations.AddField(
            model_name='originalwork',
            name='key',
            field=models.CharField(
                blank=True, max_length=30, verbose_name='key'
            ),
        ),
    ]
