# Generated by Django 2.1.11 on 2019-08-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('panta', '0065_auto_20190715_0320')]

    operations = [
        migrations.AlterField(
            model_name='basetranslator',
            name='type',
            field=models.CharField(
                choices=[
                    ('hb', 'human being'),
                    ('tm', 'translation memory'),
                    ('ai', 'artificial intelligence'),
                ],
                max_length=5,
                verbose_name='type',
            ),
        )
    ]
