# Generated by Django 2.1.11 on 2019-08-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('panta', '0066_auto_20190827_1608')]

    operations = [
        migrations.AddField(
            model_name='importantheading',
            name='pretranslated',
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name='pretranslated'
            ),
        ),
        migrations.AddField(
            model_name='workstatistics',
            name='pretranslated_count',
            field=models.PositiveIntegerField(
                default=0, verbose_name='pretranslated'
            ),
        ),
        migrations.AddField(
            model_name='workstatistics',
            name='pretranslated_percent',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name='pretranslated (%)',
            ),
        ),
    ]
