version: "3.6"

x-django: &django
  environment:
    - DOCKER=1
  env_file:
    - ./default.env
    - ./local.env
  volumes:
    - django_logs:/project/logs
    - .:/project/django
  stdin_open: true
  tty: true
  restart: always
  depends_on:
    - db
    - redis
  image: django:latest
  build:
    context: .
    dockerfile: ./docker/Dockerfile
  ports:
    - "8001:8001"

services:
  db:
    image: "${CI_REGISTRY_IMAGE}/postgres:pseudo"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: "redis:${REDIS_VERSION}"
    restart: always
    volumes:
      - redis:/data
    command: redis-server --appendonly yes
    sysctls:
      net.core.somaxconn: "511"

  django:
    <<: *django
    command: python manage.py runserver 0.0.0.0:8001

  celery:
    <<: *django
    command: celery -A langify worker -l INFO

volumes:
  postgres:
  redis:
  django_logs:
