#!/usr/bin/env python

"""
Copies poetry files and updates image versions.

Warning: This overrides the pyproject.toml file!
"""

import subprocess
from configparser import ConfigParser

versions = [
    ('POSTGRES_VERSION', '11.2-alpine'),
    ('REDIS_VERSION', '5.0-alpine'),
]

info = 'This file is auto generated by \'update_images.py\''

django_path = '/project/django'

subprocess.run(('cp', '/pyproject.toml', django_path))
subprocess.run(('cp', '/poetry.lock', django_path))

poetry = ConfigParser(strict=False)
poetry.read(f'{django_path}/Poetry.lock')
versions.append(('DJANGO_VERSION', poetry.get('metadata', 'content-hash')[1:8]))

with open(f'{django_path}/.env', 'w') as f:
    f.write(f'# {info}\n\n')
    f.writelines(f'{k}={v}\n' for k, v in versions)
    f.write('DJANGO_ENVIRONMENT=dev')

with open(f'{django_path}/image_versions.yml', 'w') as f:
    f.write(f'# {info}\n\n')
    f.write('variables:\n')
    f.writelines(f'  {k}: {v}\n' for k, v in versions)
