# Generated by Django 2.0.13 on 2019-05-22 08:11

import simple_history.models

import django.db.models.deletion
import style_guide.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name='HistoricalStyleGuide',
            fields=[
                (
                    'id',
                    models.IntegerField(
                        auto_created=True,
                        blank=True,
                        db_index=True,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name='date created'
                    ),
                ),
                (
                    'last_modified',
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name='last modified'
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=150, verbose_name='title'),
                ),
                (
                    'content',
                    models.TextField(
                        default=style_guide.utils.get_styleguide_content_from_template,
                        verbose_name='content',
                    ),
                ),
                (
                    'language',
                    models.CharField(
                        choices=[
                            ('af', 'Afrikaans'),
                            ('am', 'Amharic'),
                            ('ar', 'Arabic'),
                            ('hy', 'Armenian'),
                            ('bn', 'Bengali'),
                            ('bg', 'Bulgarian'),
                            ('my', 'Burmese'),
                            ('zh', 'Chinese'),
                            ('hr', 'Croatian'),
                            ('cs', 'Czech'),
                            ('da', 'Danish'),
                            ('nl', 'Dutch'),
                            ('en', 'English'),
                            ('fa', 'Farsi'),
                            ('fi', 'Finnish'),
                            ('fr', 'French'),
                            ('grt', 'Garo'),
                            ('de', 'German'),
                            ('hi', 'Hindi'),
                            ('hu', 'Hungarian'),
                            ('is', 'Icelandic'),
                            ('ilo', 'Ilocano'),
                            ('id', 'Indonesian'),
                            ('it', 'Italian'),
                            ('ja', 'Japanese'),
                            ('kha', 'Khasi'),
                            ('rw', 'Kinyarwanda'),
                            ('ko', 'Korean'),
                            ('lv', 'Latvian'),
                            ('lt', 'Lithuanian'),
                            ('lus2', 'Lushai'),
                            ('mk', 'Macedonian'),
                            ('mg', 'Malagasy'),
                            ('ms', 'Malay'),
                            ('mr', 'Marathi'),
                            ('lus', 'Mizo'),
                            ('no', 'Norwegian'),
                            ('hil', 'Panayan'),
                            ('pl', 'Polish'),
                            ('pt', 'Portuguese'),
                            ('ro', 'Romanian'),
                            ('ru', 'Russian'),
                            ('sr', 'Serbian'),
                            ('ksw', 'Sgaw Karen'),
                            ('si', 'Sinhala'),
                            ('sk', 'Slovak'),
                            ('es', 'Spanish'),
                            ('sw', 'Swahili'),
                            ('sv', 'Swedish'),
                            ('tl', 'Tagalog'),
                            ('ta', 'Tamil'),
                            ('te', 'Telugu'),
                            ('th', 'Thai'),
                            ('tr', 'Turkish'),
                            ('uk', 'Ukrainian'),
                            ('ur', 'Urdu'),
                            ('vi', 'Vietnamese'),
                        ],
                        db_index=True,
                        max_length=7,
                        verbose_name='language',
                    ),
                ),
                (
                    'history_id',
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ('history_date', models.DateTimeField()),
                (
                    'history_change_reason',
                    models.CharField(max_length=100, null=True),
                ),
                (
                    'history_type',
                    models.CharField(
                        choices=[
                            ('+', 'Created'),
                            ('~', 'Changed'),
                            ('-', 'Deleted'),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    'history_user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='historicalstyleguides',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'historical style guide',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StyleGuide',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='date created'
                    ),
                ),
                (
                    'last_modified',
                    models.DateTimeField(
                        auto_now=True, verbose_name='last modified'
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=150, verbose_name='title'),
                ),
                (
                    'content',
                    models.TextField(
                        default=style_guide.utils.get_styleguide_content_from_template,
                        verbose_name='content',
                    ),
                ),
                (
                    'language',
                    models.CharField(
                        choices=[
                            ('af', 'Afrikaans'),
                            ('am', 'Amharic'),
                            ('ar', 'Arabic'),
                            ('hy', 'Armenian'),
                            ('bn', 'Bengali'),
                            ('bg', 'Bulgarian'),
                            ('my', 'Burmese'),
                            ('zh', 'Chinese'),
                            ('hr', 'Croatian'),
                            ('cs', 'Czech'),
                            ('da', 'Danish'),
                            ('nl', 'Dutch'),
                            ('en', 'English'),
                            ('fa', 'Farsi'),
                            ('fi', 'Finnish'),
                            ('fr', 'French'),
                            ('grt', 'Garo'),
                            ('de', 'German'),
                            ('hi', 'Hindi'),
                            ('hu', 'Hungarian'),
                            ('is', 'Icelandic'),
                            ('ilo', 'Ilocano'),
                            ('id', 'Indonesian'),
                            ('it', 'Italian'),
                            ('ja', 'Japanese'),
                            ('kha', 'Khasi'),
                            ('rw', 'Kinyarwanda'),
                            ('ko', 'Korean'),
                            ('lv', 'Latvian'),
                            ('lt', 'Lithuanian'),
                            ('lus2', 'Lushai'),
                            ('mk', 'Macedonian'),
                            ('mg', 'Malagasy'),
                            ('ms', 'Malay'),
                            ('mr', 'Marathi'),
                            ('lus', 'Mizo'),
                            ('no', 'Norwegian'),
                            ('hil', 'Panayan'),
                            ('pl', 'Polish'),
                            ('pt', 'Portuguese'),
                            ('ro', 'Romanian'),
                            ('ru', 'Russian'),
                            ('sr', 'Serbian'),
                            ('ksw', 'Sgaw Karen'),
                            ('si', 'Sinhala'),
                            ('sk', 'Slovak'),
                            ('es', 'Spanish'),
                            ('sw', 'Swahili'),
                            ('sv', 'Swedish'),
                            ('tl', 'Tagalog'),
                            ('ta', 'Tamil'),
                            ('te', 'Telugu'),
                            ('th', 'Thai'),
                            ('tr', 'Turkish'),
                            ('uk', 'Ukrainian'),
                            ('ur', 'Urdu'),
                            ('vi', 'Vietnamese'),
                        ],
                        max_length=7,
                        unique=True,
                        verbose_name='language',
                    ),
                ),
            ],
            options={
                'verbose_name': 'style guide',
                'verbose_name_plural': 'style guides',
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
