# Generated by Django 2.0.13 on 2019-05-24 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('style_guide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='date created'
                    ),
                ),
                (
                    'last_modified',
                    models.DateTimeField(
                        auto_now=True, verbose_name='last modified'
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        help_text='Warning: This field might contain HTML from untrusted sources!',
                        max_length=150,
                        verbose_name='title',
                    ),
                ),
                (
                    'content',
                    models.TextField(
                        help_text='Warning: This field might contain HTML from untrusted sources!',
                        verbose_name='content',
                    ),
                ),
                (
                    'style_guide',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='issues',
                        to='style_guide.StyleGuide',
                        verbose_name='style guide',
                    ),
                ),
            ],
            options={
                'verbose_name': 'issue',
                'verbose_name_plural': 'issues',
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=40, unique=True, verbose_name='name'
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        max_length=40, unique=True, verbose_name='slug'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='tags',
            field=models.ManyToManyField(
                blank=True,
                related_name='issues',
                to='style_guide.Tag',
                verbose_name='tags',
            ),
        ),
        migrations.AddField(
            model_name='issue',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='issues',
                to=settings.AUTH_USER_MODEL,
                verbose_name='user',
            ),
        ),
    ]
