# Generated by Django 2.0.13 on 2019-06-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('style_guide', '0003_auto_20190530_1358')]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='diff',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Warning: This field might contain HTML from untrusted sources!',
                verbose_name='difference',
            ),
        )
    ]
