# Generated by Django 2.1.12 on 2019-11-20 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('style_guide', '0008_auto_20191119_1926')]

    operations = [
        migrations.AddField(
            model_name='issuecomment',
            name='issue',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='issues',
                to='style_guide.Issue',
                verbose_name='issues',
            ),
        )
    ]
