# Generated by Django 2.1.12 on 2020-02-11 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('style_guide', '0012_auto_20200130_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueReaction',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='date created'
                    ),
                ),
                (
                    'last_modified',
                    models.DateTimeField(
                        auto_now=True, verbose_name='last modified'
                    ),
                ),
                (
                    'content',
                    models.CharField(
                        help_text='Warning: This field might contain HTML from untrusted sources!',
                        max_length=20,
                        verbose_name='content',
                    ),
                ),
                (
                    'issue',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reactions',
                        to='style_guide.Issue',
                        verbose_name='reactions',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='issuereactions',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='user',
                    ),
                ),
            ],
            options={
                'verbose_name': 'issue reaction',
                'verbose_name_plural': 'issue reactions',
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='issuecomment',
            name='issue',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='comments',
                to='style_guide.Issue',
                verbose_name='issues',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='issuereaction', unique_together={('user', 'content', 'issue')}
        ),
    ]
