# Generated by Django 2.1.12 on 2020-02-04 19:28

import simple_history.models

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('style_guide', '0012_auto_20200130_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalIssue',
            fields=[
                (
                    'id',
                    models.IntegerField(
                        auto_created=True,
                        blank=True,
                        db_index=True,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        help_text='Warning: This field might contain HTML from untrusted sources!',
                        max_length=150,
                        verbose_name='title',
                    ),
                ),
                (
                    'content',
                    models.TextField(
                        help_text='Warning: This field might contain HTML from untrusted sources!',
                        verbose_name='content',
                    ),
                ),
                (
                    'diff',
                    models.TextField(
                        blank=True,
                        default='',
                        help_text='Warning: This field might contain HTML from untrusted sources!',
                        verbose_name='difference',
                    ),
                ),
                (
                    'history_id',
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ('history_date', models.DateTimeField()),
                (
                    'history_change_reason',
                    models.CharField(max_length=100, null=True),
                ),
                (
                    'history_type',
                    models.CharField(
                        choices=[
                            ('+', 'Created'),
                            ('~', 'Changed'),
                            ('-', 'Deleted'),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    'history_user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='historicalissues',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'style_guide',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='style_guide.StyleGuide',
                        verbose_name='style guide',
                    ),
                ),
            ],
            options={
                'verbose_name': 'historical issue',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        )
    ]
