# Generated by Django 2.1.12 on 2020-02-16 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('style_guide', '0013_auto_20200211_1504'),
        ('style_guide', '0013_historicalissue'),
    ]

    operations = []
