# Generated by Django 2.0 on 2017-12-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("path", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="privileges",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="path.Privilege",
                verbose_name="privileges",
            ),
        )
    ]
