# Generated by Django 2.0.1 on 2018-01-22 10:01

import imagekit.models.fields

import django.contrib.postgres.fields.jsonb
import path.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("path", "0002_auto_20171222_1245")]

    operations = [
        migrations.RemoveField(model_name="historicaluser", name="image"),
        migrations.RemoveField(model_name="user", name="image"),
        migrations.AddField(
            model_name="historicaluser",
            name="avatar",
            field=models.TextField(
                blank=True,
                help_text="Profile image.",
                max_length=100,
                null=True,
                verbose_name="image",
            ),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="avatar_crop",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict, verbose_name="image crop"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                help_text="Profile image.",
                null=True,
                upload_to=path.models.user_avatar_path,
                verbose_name="image",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_crop",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict, verbose_name="image crop"
            ),
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="name_display",
            field=models.CharField(
                choices=[
                    ("full", "full name"),
                    ("first", "first name"),
                    ("user", "username"),
                ],
                default="full",
                help_text="Name that is visible on the website for others.",
                max_length=5,
                verbose_name="name display",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name_display",
            field=models.CharField(
                choices=[
                    ("full", "full name"),
                    ("first", "first name"),
                    ("user", "username"),
                ],
                default="full",
                help_text="Name that is visible on the website for others.",
                max_length=5,
                verbose_name="name display",
            ),
        ),
    ]
