# Generated by Django 2.0.5 on 2018-05-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("path", "0004_auto_20180413_0907")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="public_id",
            field=models.CharField(
                blank=True, max_length=8, null=True, unique=True
            ),
        )
    ]
