# Generated by Django 2.0.5 on 2018-05-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("path", "0006_assign_public_ids")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="public_id",
            field=models.CharField(
                max_length=8, unique=True, verbose_name="public ID"
            ),
        )
    ]
