# Generated by Django 2.0.10 on 2019-01-22 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("path", "0015_auto_20181224_1642")]

    operations = [
        migrations.AlterField(
            model_name="historicalemailaddress",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        )
    ]
