# Generated by Django 2.0.13 on 2019-03-15 05:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("path", "0016_auto_20190122_0837")]

    operations = [
        migrations.AlterField(
            model_name="historicaluser",
            name="avatar_crop",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, verbose_name="image crop"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar_crop",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, verbose_name="image crop"
            ),
        ),
    ]
