# Generated by Django 2.0.13 on 2019-03-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("path", "0017_auto_20190315_0523")]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="description",
            field=models.TextField(
                blank=True,
                help_text=(
                    "Warning: "
                    "This field might contain HTML from untrusted sources!"
                ),
                max_length=5000,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="education",
            field=models.TextField(
                blank=True,
                help_text=(
                    "Warning: "
                    "This field might contain HTML from untrusted sources!"
                ),
                max_length=5000,
                verbose_name="education",
            ),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="experience",
            field=models.TextField(
                blank=True,
                help_text=(
                    "Warning: "
                    "This field might contain HTML from untrusted sources!"
                ),
                max_length=5000,
                verbose_name="experience",
            ),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="is_verified",
            field=models.BooleanField(
                default=False, verbose_name="is verified"
            ),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="show_age",
            field=models.BooleanField(default=False, verbose_name="show age"),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="show_country",
            field=models.BooleanField(
                default=False, verbose_name="show country"
            ),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="show_description",
            field=models.BooleanField(
                default=False, verbose_name="show description"
            ),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="show_education",
            field=models.BooleanField(
                default=False, verbose_name="show education"
            ),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="show_experience",
            field=models.BooleanField(
                default=False, verbose_name="show experience"
            ),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="show_full_name",
            field=models.BooleanField(
                default=False, verbose_name="show full name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.TextField(
                blank=True,
                help_text=(
                    "Warning: "
                    "This field might contain HTML from untrusted sources!"
                ),
                max_length=5000,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="education",
            field=models.TextField(
                blank=True,
                help_text=(
                    "Warning: "
                    "This field might contain HTML from untrusted sources!"
                ),
                max_length=5000,
                verbose_name="education",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="experience",
            field=models.TextField(
                blank=True,
                help_text=(
                    "Warning: "
                    "This field might contain HTML from untrusted sources!"
                ),
                max_length=5000,
                verbose_name="experience",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(
                default=False, verbose_name="is verified"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="show_age",
            field=models.BooleanField(default=False, verbose_name="show age"),
        ),
        migrations.AddField(
            model_name="user",
            name="show_country",
            field=models.BooleanField(
                default=False, verbose_name="show country"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="show_description",
            field=models.BooleanField(
                default=False, verbose_name="show description"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="show_education",
            field=models.BooleanField(
                default=False, verbose_name="show education"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="show_experience",
            field=models.BooleanField(
                default=False, verbose_name="show experience"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="show_full_name",
            field=models.BooleanField(
                default=False, verbose_name="show full name"
            ),
        ),
    ]
