# Generated by Django 2.0.13 on 2019-04-01 11:38

import path.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("path", "0018_auto_20190327_1936")]

    operations = [
        migrations.AlterField(
            model_name="historicaluser",
            name="address",
            field=models.CharField(
                blank=True,
                max_length=50,
                validators=[
                    path.validators.html_free,
                    path.validators.contains_captialized_word,
                ],
                verbose_name="address",
            ),
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="address_2",
            field=models.CharField(
                blank=True,
                max_length=50,
                validators=[path.validators.html_free],
                verbose_name="address 2",
            ),
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="city",
            field=models.CharField(
                blank=True,
                max_length=50,
                validators=[
                    path.validators.html_free,
                    path.validators.contains_captialized_word,
                ],
                verbose_name="city",
            ),
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="first_name",
            field=models.CharField(
                blank=True,
                max_length=30,
                validators=[
                    path.validators.html_free,
                    path.validators.contains_captialized_word,
                ],
                verbose_name="first name",
            ),
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="last_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                validators=[
                    path.validators.html_free,
                    path.validators.contains_captialized_word,
                ],
                verbose_name="last name",
            ),
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=40,
                validators=[path.validators.html_free],
                verbose_name="phone number",
            ),
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="pseudonym",
            field=models.CharField(
                blank=True,
                help_text="Use this name instead of the real name.",
                max_length=100,
                validators=[
                    path.validators.html_free,
                    path.validators.contains_captialized_word,
                ],
                verbose_name="pseudonym",
            ),
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="state",
            field=models.CharField(
                blank=True,
                max_length=50,
                validators=[
                    path.validators.html_free,
                    path.validators.contains_captialized_word,
                ],
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(
                blank=True,
                max_length=50,
                validators=[
                    path.validators.html_free,
                    path.validators.contains_captialized_word,
                ],
                verbose_name="address",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="address_2",
            field=models.CharField(
                blank=True,
                max_length=50,
                validators=[path.validators.html_free],
                verbose_name="address 2",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True,
                max_length=50,
                validators=[
                    path.validators.html_free,
                    path.validators.contains_captialized_word,
                ],
                verbose_name="city",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                max_length=30,
                validators=[
                    path.validators.html_free,
                    path.validators.contains_captialized_word,
                ],
                verbose_name="first name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                validators=[
                    path.validators.html_free,
                    path.validators.contains_captialized_word,
                ],
                verbose_name="last name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=40,
                validators=[path.validators.html_free],
                verbose_name="phone number",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="pseudonym",
            field=models.CharField(
                blank=True,
                help_text="Use this name instead of the real name.",
                max_length=100,
                validators=[
                    path.validators.html_free,
                    path.validators.contains_captialized_word,
                ],
                verbose_name="pseudonym",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="state",
            field=models.CharField(
                blank=True,
                max_length=50,
                validators=[
                    path.validators.html_free,
                    path.validators.contains_captialized_word,
                ],
                verbose_name="state",
            ),
        ),
    ]
