# Generated by Django 2.1.12 on 2019-10-21 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('path', '0022_auto_20190613_1122')]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flagged',
            field=models.ManyToManyField(
                related_name='flagged_by', to=settings.AUTH_USER_MODEL
            ),
        )
    ]
