# Generated by Django 2.1.12 on 2019-11-24 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0023_auto_20191107_1405'),
        ('path', '0024_auto_20191023_0204'),
    ]

    operations = []
