# Generated by Django 2.1.12 on 2020-03-04 22:47

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('path', '0027_auto_20200130_1847')]

    operations = [
        migrations.CreateModel(
            name='OIDCUser',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'sub',
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name='Subject identifier',
                    ),
                ),
                (
                    'userinfo',
                    django.contrib.postgres.fields.jsonb.JSONField(
                        verbose_name='Subject extra data'
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='oidc_user',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'OpenID Connect user',
                'verbose_name_plural': 'OpenID Connect users',
            },
        )
    ]
