# Generated by Django 2.0.4 on 2018-05-15 14:10

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("misc", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPage",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True,
                        blank=True,
                        db_index=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="date created"
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="last modified"
                    ),
                ),
                ("slug", models.SlugField(verbose_name="slug")),
                (
                    "content",
                    models.TextField(
                        help_text="Email addresses and numbers beginning with a + are obfuscated.",
                        verbose_name="content",
                    ),
                ),
                (
                    "history_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("history_date", models.DateTimeField()),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical page",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modified"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                (
                    "content",
                    models.TextField(
                        help_text="Email addresses and numbers beginning with a + are obfuscated.",
                        verbose_name="content",
                    ),
                ),
                ("rendered", models.TextField(verbose_name="rendered content")),
                (
                    "protected",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=254),
                        default=list,
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name": "page",
                "verbose_name_plural": "pages",
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
    ]
