# Generated by Django 2.0.6 on 2018-07-09 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("misc", "0002_historicalpage_page")]

    operations = [
        migrations.AlterField(
            model_name="historicalpage",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="historicalpages",
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
