# Generated by Django 2.0.12 on 2019-02-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("misc", "0004_attachment")]

    operations = [
        migrations.AddField(
            model_name="historicalpage",
            name="contact_button",
            field=models.BooleanField(
                default=False, verbose_name="contact button"
            ),
        ),
        migrations.AddField(
            model_name="historicalpage",
            name="public",
            field=models.BooleanField(default=False, verbose_name="public"),
        ),
        migrations.AddField(
            model_name="page",
            name="contact_button",
            field=models.BooleanField(
                default=False, verbose_name="contact button"
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="public",
            field=models.BooleanField(default=False, verbose_name="public"),
        ),
    ]
