# Generated by Django 2.0.13 on 2019-04-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("misc", "0005_auto_20190212_1806")]

    operations = [
        migrations.AlterField(
            model_name="developercomment",
            name="content",
            field=models.TextField(
                help_text=(
                    "Warning: "
                    "This field might contain HTML from untrusted sources!"
                ),
                max_length=2000,
                verbose_name="content",
            ),
        )
    ]
