# Generated by Django 2.0.6 on 2018-06-19 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("panta", "0012_auto_20180617_1849")]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="name")),
                (
                    "segments",
                    models.ManyToManyField(
                        related_name="all_classes",
                        to="panta.OriginalSegment",
                        verbose_name="segments",
                    ),
                ),
            ],
            options={"verbose_name": "class", "verbose_name_plural": "classes"},
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="name"
                    ),
                ),
                (
                    "segments",
                    models.ManyToManyField(
                        related_name="all_tags",
                        to="panta.OriginalSegment",
                        verbose_name="segments",
                    ),
                ),
            ],
            options={"verbose_name": "tag", "verbose_name_plural": "tags"},
        ),
        migrations.AddField(
            model_name="class",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="white_estate.Tag",
                verbose_name="tag",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="class", unique_together={("name", "tag")}
        ),
    ]
