# Generated by Django 2.0.9 on 2018-10-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panta", "0021_auto_20181022_0711"),
        ("white_estate", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sentence",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        max_length=1500, unique=True, verbose_name="content"
                    ),
                ),
                (
                    "count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="count"
                    ),
                ),
                (
                    "segments",
                    models.ManyToManyField(
                        related_name="sentences",
                        to="panta.OriginalSegment",
                        verbose_name="segments",
                    ),
                ),
            ],
            options={
                "verbose_name": "sentence",
                "verbose_name_plural": "sentences",
            },
        )
    ]
