# Generated by Django 2.0.12 on 2019-02-11 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panta", "0035_auto_20190201_0920"),
        ("white_estate", "0002_sentence"),
    ]

    operations = [
        migrations.CreateModel(
            name="OriginalSegmentSentenceRelation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="panta.OriginalSegment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OriginalSentence",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(unique=True, verbose_name="content"),
                ),
                (
                    "count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="count"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "segments",
                    models.ManyToManyField(
                        related_name="sentences",
                        through="white_estate.OriginalSegmentSentenceRelation",
                        to="panta.OriginalSegment",
                        verbose_name="segments",
                    ),
                ),
            ],
            options={
                "verbose_name": "original sentence",
                "verbose_name_plural": "original sentences",
            },
        ),
        migrations.RemoveField(model_name="sentence", name="segments"),
        migrations.DeleteModel(name="Sentence"),
        migrations.AddField(
            model_name="originalsegmentsentencerelation",
            name="sentence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="white_estate.OriginalSentence",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="originalsegmentsentencerelation",
            unique_together={("segment", "number")},
        ),
    ]
